
linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
#    - unused # intentionally commented to avoid unused func warning as this repo is library
#    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gocyclo
    - gosec
    - gosimple
#   - govet # intentionally disabled because we choose readability over performance
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc # pre-allocate slices with define size if the slice size is known in advance
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - lll
    - wsl # While space linter

run:
  issues-exit-code: 1
  go: '1.18'

issues:
  exclude-rules:
    - path: '(.+)test\.go'
      linters:
      - govet # Test code field alignment for sake of space is not a concern
      - dupl
    - path: '(.+)test\.go'
      text: importShadow
    - path: 'example_test\.go'
      linters:
      - goconst
    - path: 'flags/cert_test\.go'
      linters:
      - goconst
    - path: 'flags/utils_test\.go'
      linters:
      - lll