on:
  push:

jobs:
  build-php-client:
    runs-on: ubuntu-24.04
    steps:
    - name: Get list of all packages
      run: sudo apt update
    - name: Install prerequisites
    # Rust is already installed, as well as rustup
    # But it doesn't work when we run `make sudo` later on, so we have to reinstall
    # with apt
      run: |
        sudo apt -y install \
          php-dev \
          phpunit \
          build-essential \
          protobuf-compiler \
          rustup
    - uses: actions/checkout@v4
    - name: Download and install latest Rust
      run: sudo rustup default stable
    - name: Build and install PHP client
      # sudo required for install step
      run: sudo make
    - name: Install prerequisites using go
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go get google.golang.org/grpc
      working-directory: aerospike-connection-manager
      shell: sudo bash -e {0}
    - name: Fix symlinkage of protobuf
      # Binaries aren't available in PATH by default
      run: |
          test -f /root/go/bin/protoc-gen-go
          test -f /root/go/bin/protoc-gen-go-grpc
          sudo ln -s /root/go/bin/protoc-gen-go /usr/bin/protoc-gen-go
          sudo ln -s /root/go/bin/protoc-gen-go-grpc /usr/bin/protoc-gen-go-grpc
    - name: Build and run ACM
      run: sudo make
      working-directory: aerospike-connection-manager
