on:
  push:

jobs:
  build-php-client:
    runs-on: ubuntu-24.04
    steps:
    - name: Get list of all packages
      run: sudo apt update
    - name: Install prerequisites
      run: |
        sudo apt -y install \
          php-dev \
          phpunit \
          build-essential \
          protobuf-compiler
    - name: Fix symlinkage of protobuf
      # Binaries aren't available in PATH by default
      run: |
          sudo ln -s /root/go/bin/protoc-gen-go /usr/bin/
          sudo ln -s /root/go/bin/protoc-gen-go-grpc /usr/bin/
    - uses: actions/checkout@v4
    - name: Allow sudo to find cargo
      run: sudo ln -s $(which cargo) /usr/bin/
    - name: Download and install latest Rust
      run: sudo rustup default stable
    - name: Build and install PHP client
      # sudo required for install step
      run: sudo make
    - name: Install prerequisites using go
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go get google.golang.org/grpc
    - name: Build and run ACM
      run: make
      working-directory: aerospike-connection-manager
