on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: docker run -d --name aerospike -p 3000:3000 aerospike/aerospike-server
    # TODO: this should be committed in repo
    - name: Build client
      run: |
        chmod +x ./install_as_php_client_linux.sh
        sudo ./install_as_php_client_linux.sh
      working-directory: build
