on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [
          # runner os, script name
          [ubuntu-24.04, install_as_php_client_linux.sh],
          [macos-13, install_as_php_client_mac.zsh]
        ]
      fail-fast: false
    runs-on: ${{ matrix.os[0] }}
    steps:
    - uses: actions/checkout@v4
    - run: brew install docker
      if: ${{ matrix.os[1] == 'mac' }}
    - run: brew install colima
      if: ${{ matrix.os[1] == 'mac' }}
    - run: colima start
      if: ${{ matrix.os[1] == 'mac' }}
    - run: docker run -d --name aerospike -p 3000:3000 aerospike/aerospike-server
    # TODO: this should be committed in repo
    - name: Build client
      run: |
        chmod +x ./${{ matrix.os[1] }}
        sudo ./${{ matrix.os[1] }}
      working-directory: build
