on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [
          # runner os,
          ubuntu-24.04,
          macos-13
        ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: brew install docker
      if: ${{ runner.os == 'macOS' }}
    - run: brew install colima
      if: ${{ runner.os == 'macOS' }}
    - run: colima start
      if: ${{ runner.os == 'macOS' }}
    - run: docker run -d --name aerospike -p 3000:3000 aerospike/aerospike-server
    # TODO: this should be committed in repo
    - name: Build client on mac
      run: ./install_as_php_client_mac.zsh
      working-directory: build
    - name: Build client on linux
      run: sudo ./install_as_php_client_linux.sh
      working-directory: build
