on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [
          # runner os,
          ubuntu-24.04,
          macos-13
        ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: brew install docker
      if: ${{ runner.os == 'macOS' }}
    - run: brew install colima
      if: ${{ runner.os == 'macOS' }}
    - run: colima start
      if: ${{ runner.os == 'macOS' }}
    - run: docker run -d --name aerospike -p 3000:3000 aerospike/aerospike-server
    # TODO: this should be committed in repo
    - run: cat asld.toml asld.toml.template
      working-directory: aerospike-connection-manager
    - if: ${{ runner.os == 'macOS' }}
      name: Build client on mac
      run: ./install_as_php_client_mac.zsh
      working-directory: build
    - if: ${{ runner.os == 'Linux' }}
      name: Build client on linux
      # On Github Actions, we don't want this script to fail
      # but for users running the script manually, it should be idempotent and allowed to fail in case
      # they want to rerun it
      run: sudo bash -e ./build_on_linux.bash
      working-directory: build
