on:
  push:

jobs:
  build-php-client:
    runs-on: ubuntu-24.04
    steps:
    # TODO: run EE server from shared repo, not the Python client repo
    - uses: actions/checkout@v4
      with:
        repository: aerospike/aerospike-client-python
        ref: 6db93eb
        sparse-checkout: |
          .github
    - uses: ./.github/actions/run-ee-server

    - name: Checkout PHP client repo
      uses: actions/checkout@v4
    - name: Get list of all packages
      run: sudo apt update
    - name: Install prerequisites
    # Rust is already installed, as well as rustup
    # But it doesn't work when we run `make sudo` later on, so we have to reinstall
    # with apt
      run: |
        sudo apt -y install \
          php-dev \
          phpunit \
          build-essential \
          protobuf-compiler \
          rustup
    - uses: actions/checkout@v4
    - name: Download and install latest Rust
      run: sudo rustup default stable
    - name: Install prerequisites using go
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go get google.golang.org/grpc
      working-directory: aerospike-connection-manager
      shell: sudo bash -e {0}
    - name: Build and run ACM
      run: |
        export PATH="$PATH:$(go env GOPATH)/bin"
        make daemonize
      shell: sudo bash -e {0}
      working-directory: aerospike-connection-manager
    - run: sudo systemctl status aerospike-connection-manager
    - name: Build and install PHP client, then run tests
      run: sudo make test
